G:
  _target_: diffusers.UNet2DModel
  sample_size: 32
  in_channels: 1
  out_channels: 1
  block_out_channels: [128, 128, 256, 256, 512, 512]
  down_block_types:
    - DownBlock2D     # a regular ResNet downsampling block
    - DownBlock2D
    - DownBlock2D
    - DownBlock2D
    - AttnDownBlock2D # a ResNet downsampling block with spatial self-attention
    - DownBlock2D
  up_block_types:
    - UpBlock2D       # a regular ResNet upsampling block
    - AttnUpBlock2D   # a ResNet upsampling block with spatial self-attention
    - UpBlock2D
    - UpBlock2D
    - UpBlock2D
    - UpBlock2D
D:
  _target_: diffusers.UNet2DModel
  sample_size: 28
  in_channels: 1
  out_channels: 1
  block_out_channels: [128, 128, 256, 256, 512, 512]
  down_block_types:
    - DownBlock2D     # a regular ResNet downsampling block
    - DownBlock2D
    - DownBlock2D
    - DownBlock2D
    - AttnDownBlock2D # a ResNet downsampling block with spatial self-attention
    - DownBlock2D
  up_block_types:
    - UpBlock2D       # a regular ResNet upsampling block
    - AttnUpBlock2D   # a ResNet upsampling block with spatial self-attention
    - UpBlock2D
    - UpBlock2D
    - UpBlock2D
    - UpBlock2D