G:
  _target_: diffusers.UNet2DModel
  sample_size: 32
  in_channels: 1
  out_channels: 1
  block_out_channels:
    - 128
    - 128
    - 256
  down_block_types:
    - DownBlock2D     # 32 -> 16. A regular ResNet downsampling block. 
    - AttnDownBlock2D # 16 -> 8 . A ResNet downsampling block with spatial self-attention
    - DownBlock2D     #  8 -> 4 . A regular ResNet downsampling block. 
  up_block_types:
    - UpBlock2D       #  4 -> 8 . A regular ResNet upsampling block
    - AttnUpBlock2D   #  8 -> 16. A ResNet upsampling block with spatial self-attention
    - UpBlock2D       # 16 -> 32. A regular ResNet upsampling block. 