project_name: MNIST

defaults:
  - _self_
  - model: g
  - loss: diffusion

num_sample: 16

grid: False

paths:
  root_dir: ${oc.env:PROJECT_ROOT}
  output_dir: null
  model_G_path: null
  model_B_path: null

data:
  dataset_path: ylecun/mnist
  preprocess:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: [32, 32]
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.1307]
        std: [0.3081]
  batch_size: 8

hydra:
  output_subdir: null

noise_scheduler:
  _target_: diffusers.DDPMScheduler
  num_train_timesteps: 1000