project_name: MNIST

defaults:
  - _self_
  - model: size_32_g
  - loss: diffusion
  - noise_scheduler: diffusion

num_sample: 64

grid: False

paths:
  root_dir: ${oc.env:PROJECT_ROOT}
  output_dir: null
  model_G_path: null
  model_B_path: null

data:
  dataset_path: ylecun/mnist
  preprocess:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: [32, 32]
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.1307]
        std: [0.3081]
  batch_size: 64

hydra:
  output_subdir: null

method: diffusion # diffusion | euler
